### ISSUE TITLE
Implementation Plan for SQS Queue Adapter

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper-adapter-sqs#5]
The Queue Port is built to handle a message asynchronously for a serverless api, the serverless api can dispatch or post a task, then make a web hook post to the serverless api to process the task in an async way. This allows a serverless process to trigger tasks but not have to wait for them to complete. 

## Background

The current queue API https://docs.hyper.io/queue-api - takes a queue name, a target url and optional secret to create
the queue. I need to store this state, so when a message event is triggered I can retrieve the state and dispatch the task to the appropriate party based on the target and secret. As I dig into implementing the adapter for AWS, I have a couple of options. 

### Option 1

* Create Cloudfront script to generate SQS endpoints and lambda
* Create SQS and lambda function to be triggered by SQS
* PostMessage to SQS
* Lambda gets triggered
* Lambda calls target to publish task

### Option 2

* Is to create an s3 bucket and json document to store the queue name and webhook target and secret
* create sqs queue
* listen for messages in queue via long polling
* load the queues from the s3 bucket
* when a post message is called post in sqs
* retrieve the message from sqs and get the target and secret info then dispatch to target

### Thoughts

With option one, the state is hard coded in the lambda function, so for each queue a new lambda function will be created and it will contain the target and secret based on a template. With option two, I use s3 to store the state and every time the service is restarted I will need to read the s3 bucket to pull the state and setup each queue in memory. Then poll the sqs queue for messages.

**Comment by TillaTheHun0** [comment]
Option 1 sounds more conventional, but option 2 sounds easier to implement as well as easier to cleanup, in the case of deleting a queue ie. deleting a queue is just deleting a document in s3 and then the queue itself. Option 1 involves tearing down lambdas in addition to the queue.

## Option 1

### benefits
- seems more conventional
- unlike option 2, no additional burden put on the hyper service (polling)
### cons
- seems more difficult to implement
- seems more difficult to tear down
- pretty tightly coupled to AWS paradigms
- could be more difficult to estimate cost of solution on AWS

## Option 2

### benefits
- relative to option 1, easier to implement
- easy to tear down queues
- not relying on AWS paradigms as much as option 1 (it just's blob storage and polling)
### cons
- Polling could bog down the hyper service
- Polling interval could produce undesirable delays in dispatch to target

## Some questions:

For the long polling in option 2, would there be an interval for each queue, or would all queues be polled on the same interval? To many independent polling intervals seems problematic for the hyper service.

What would the polling interval be? Too long of an interval, I could see undesirable delay from posting to hyper to dispatching the job. Too short an interval could bog down the hyper service with polling instead of handling incoming requests.

Given what I know on the above solutions, I lean towards option 2.

## Option 3?

Perhaps a hybrid of the option 1 and option 2
- Create an SQS queue
- Create a doc in s3 that stores the state of each queue
- Create a lambda, that runs on cron, that fetches from s3 and checks SQS, perhaps once, or for a couple intervals (polling).
- If unprocessed jobs are found, lambda dispatches to target

Option 3 is easy to create queues (doc in s3 and SQS) and to cleanup queues (delete doc from s3) and also doesn't put extra load of polling on the hyper service. The hyper service just has to manage setting a single lambda triggered off of cron.

I hope I explained that well enough.

**Comment by twilson63** [comment]
Like option three, we could create one hyper queue and one lambda that manages all “hyper queues” 

we can set lambda to trigger on sqs event
Then lookup queue doc in s3 on trigger and then call target.
